version: '3.8'
services:
  movies:
    image: sanjualuru/ptm:movies
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: sanjualuru/ptm:train
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: sanjualuru/ptm:dth
    ports:
      - "83:80"
    deploy:
      replicas: 3
  
  recharge:
    image: sanjualuru/ptm:recharge
    ports:
      - "84:80"
    deploy:
      replicas: 3
